name: Build

on:
  push:
    branches:
      - main
      - tmp
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  release:
    types: [created]

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    env:
      CMAKE_C_COMPILER: ${{ matrix.compiler }}
      CMAKE_C_FLAGS: -Werror
      EMSCRIPTEN_TOOLCHAIN_FILE: ./emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        compiler: [gcc, clang-12, gcc-10]
        include:
          - compiler: "gcc"
            cmake_options: -DBUILD_EXAMPLES=ON -DENABLE_LTO=ON -DENABLE_SANITIZER=ON -DSINGLE_LIBRARY=ON
            build_example3:
          - compiler: "clang-12"
            cmake_options: -DBUILD_EXAMPLES=ON -DENABLE_LTO=OFF -DENABLE_SANITIZER=OFF -DSINGLE_LIBRARY=ON
            build_example3: yes
          - compiler: "gcc-10"
            cmake_options: -DBUILD_EXAMPLES=ON -DENABLE_LTO=OFF -DENABLE_SANITIZER=OFF -DSINGLE_LIBRARY=OFF
            build_example3: yes

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 1
      - name: Install Ubuntu Prerequisites
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install git cmake pkg-config libgl-dev libglfw3-dev freeglut3-dev
          sudo apt-get install ${{ matrix.compiler }}
      - name: Install EMSDK
        run: |
          ./get_emsdk.sh
      - name: Configure imweb
        run: |
          cmake -S . -B ./build -DCMAKE_INSTALL_PREFIX=./install/${{ matrix.os }}_${{ matrix.compiler }} ${{ matrix.cmake_options }}
      - name: Build imweb
        run: |
          cmake --build ./build --verbose
      - name: Install imweb
        run: |
          cmake --install ./build
          tree ./install/${{ matrix.os }}_${{ matrix.compiler }}
      - name: Build example3
        if: startsWith(matrix.build_example3, 'yes')
        run: |
          PKG_CONFIG_PATH=$(realpath ./install/${{ matrix.os }}_${{ matrix.compiler }}/lib/pkgconfig) cmake -S ./example3 -B ./build-example3_${{ matrix.os }}_${{ matrix.compiler }} -DCMAKE_INSTALL_PREFIX=./install/example3_${{ matrix.os }}_${{ matrix.compiler }}
          cmake --build ./build-example3_${{ matrix.os }}_${{ matrix.compiler }} --verbose
          cmake --install ./build-example3_${{ matrix.os }}_${{ matrix.compiler }} --verbose
          tree ./build-example3_${{ matrix.os }}_${{ matrix.compiler }}
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./install
      - name: Build script (CMake Toolchain)
        if: startsWith(matrix.os, 'ubuntu') && startsWith(matrix.compiler, 'gcc')
        run: |
          ./build.sh
      - name: Build script (PATH)
        if: startsWith(matrix.os, 'ubuntu') && startsWith(matrix.compiler, 'gcc')
        run: |
          unset EMSCRIPTEN_TOOLCHAIN_FILE
          source ./emsdk/emsdk_env.sh
          ./build.sh
